# Site settings
title: Max Wolffe
email: max.wolffe@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Student. Developer. Human
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.maxwolffe.com" # the base hostname & protocol for your site
twitter_username: MaxWolffe
github_username:  maxwolffe

# Build settings
markdown: kramdown
