# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Max Wolffe
tagline:          'Engineer. Student. Human.'
description:      'Engineer at LinkedIn. </br> Lifelong Learner.'
url:              http://maxwolffe.com
baseurl:          /

author:
  name:           'Max Wolffe'
  url:            https://twitter.com/maxwolffe

# Social Media Content

email: max.alan.wolffe@gmail.com
twitter_username: MaxWolffe
github_username:  maxwolffe
linkedin_username: maxwolffe
googleplus_username: 102684669296291978308
pinterest_username: maxwolffe

# Sizing

iconsize: 42px

# Dependencies:
gems:
  - jekyll-gist