# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Max Wolffe
tagline:          'Student. Developer. Human.'
description:      'Student at UC Berkeley. </br> Developer at <a href="http://bptech.berkeley.edu/" target="_blank">Blueprint</a> <br> and UGSI at <a href="http://cs61a.org/" target="_blank">CS61A</a>.'
url:              http://maxwolffe.com
baseurl:          /

author:
  name:           'Max Wolffe'
  url:            https://twitter.com/maxwolffe

# Social Media Content

email: max.wolffe@berkeley.edu
twitter_username: MaxWolffe
github_username:  maxwolffe
linkedin_username: maxwolffe
googleplus_username: 102684669296291978308
pinterest_username: maxwolffe

# Sizing

iconsize: 42px

# Dependencies:
gems:
  - jekyll-gist